// <auto-generated />
namespace Noetic.DataAccess.Sql.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class FixZipCode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixZipCode));
        
        string IMigrationMetadata.Id
        {
            get { return "201807102255132_FixZipCode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
